# Generated by Django 4.0.5 on 2022-08-23 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('whats_app', models.CharField(max_length=50, verbose_name='WhatsApp')),
                ('telegram', models.CharField(max_length=50, verbose_name='Telegram')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название банера')),
                ('image', models.ImageField(upload_to='banner-image', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='StarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории звезды')),
            ],
        ),
        migrations.CreateModel(
            name='StarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО звезды')),
                ('image', models.ImageField(upload_to='star-profile-image', verbose_name='Фото профиля')),
                ('banner', models.ImageField(upload_to='star-profile-banner', verbose_name='Баннер')),
                ('video', models.FileField(upload_to='star-profile-video', verbose_name='Видео профиля')),
                ('description', models.TextField(blank=True, null=True, verbose_name='О звезде')),
                ('deadline', models.IntegerField(verbose_name='Срок выполнения')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('category', models.ManyToManyField(related_name='star_profile', to='star.starcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_review', to='star.starprofile', verbose_name='Профиль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='star_review', to=settings.AUTH_USER_MODEL, verbose_name='Кто')),
            ],
        ),
        migrations.CreateModel(
            name='StarOrderVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='star-order-video', verbose_name='Видео')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_video', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('text', models.TextField(verbose_name='Текст')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='star.starprofile', verbose_name='Звезда')),
            ],
        ),
    ]
