# Generated by Django 4.0.5 on 2022-08-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starcategory',
            options={'verbose_name': 'Категория звезды', 'verbose_name_plural': 'Категория звезд'},
        ),
        migrations.AlterModelOptions(
            name='starprofile',
            options={'verbose_name': 'Звезда', 'verbose_name_plural': 'Звезды'},
        ),
        migrations.AlterField(
            model_name='starprofile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='star-profile-video', verbose_name='Видео профиля'),
        ),
    ]
