# Generated by Django 4.0.5 on 2022-08-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0006_order_user_starquestionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='starprofile',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ManagerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='Пользователь')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('text', models.TextField(verbose_name='Текст')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='star.starprofile', verbose_name='Звезда')),
            ],
        ),
    ]
