# Generated by Django 4.0.5 on 2022-08-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0007_remove_order_user_starprofile_status_managerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='starquestionnaire',
            name='price_region',
            field=models.CharField(default=1, max_length=50, verbose_name='Цена за выступление'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starquestionnaire',
            name='region',
            field=models.CharField(default=1, max_length=200, verbose_name='Регионы'),
            preserve_default=False,
        ),
    ]
