# Generated by Django 4.0.5 on 2022-08-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0008_starquestionnaire_price_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerorder',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='order',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
