# Generated by Django 4.0.5 on 2022-08-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0009_alter_managerorder_text_alter_order_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerorder',
            name='star',
            field=models.CharField(max_length=100, verbose_name='Звезда'),
        ),
    ]
