# Generated by Django 4.0.5 on 2022-08-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0010_alter_managerorder_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerorder',
            name='image',
            field=models.ImageField(default=1, upload_to='order_pay', verbose_name='Фото чека'),
            preserve_default=False,
        ),
    ]
