# Generated by Django 4.0.5 on 2022-08-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0012_starvideo_delete_starordervideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='starprofile',
            name='video',
            field=models.FileField(default=1, upload_to='star-video', verbose_name='Видео'),
            preserve_default=False,
        ),
    ]
