# Generated by Django 4.0.5 on 2022-08-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0013_starprofile_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='starcategory',
            name='category_id',
            field=models.CharField(default=1, max_length=10, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
